---
title: "Threatened Species: Global Vertebrates (2021)"
author: "Lewis Blagogie"
date: "6/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
SYB64_313_202110_Threatened_Species <- read_csv("C:/Users/Lewis/Desktop/DATA/clim data/SYB64_313_202110_Threatened Species.csv")
View(SYB64_313_202110_Threatened_Species)

library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r, echo=FALSE, message=FALSE}

sp1 <- SYB64_313_202110_Threatened_Species %>% filter(...4 == 'Threatened Species: Vertebrates (number)') %>% dplyr::select(`Threatened species`, ...3, ...4, ...5) %>% rename("region" = `Threatened species`, "Year" = ...3, "Species" = ...4, "Value" = ...5) %>% filter(Year == 2021) %>% mutate(Species = recode(Species, "Threatened Species: Vertebrates (number)" = "vertebrates")) %>% dplyr::select(region, Value, Year) %>% dplyr::select(region, Value) %>% arrange(desc(Value))

```

```{r, echo=FALSE, message=FALSE}
sp2 <- SYB64_313_202110_Threatened_Species %>% filter(...4 == 'Threatened Species: Invertebrates (number)') %>% dplyr::select(`Threatened species`, ...3, ...4, ...5) %>% rename("region" = `Threatened species`, "Year" = ...3, "Species" = ...4, "Value" = ...5) %>% filter(Year == 2021) %>% mutate(Species = recode(Species, "Threatened Species: Vertebrates (number)" = "Inertebrates")) %>% dplyr::select(region, Value, Year) %>% dplyr::select(region, Value)
```

```{r, echo=FALSE, message=FALSE}
sp3 <- SYB64_313_202110_Threatened_Species %>% filter(...4 == 'Threatened Species: Plants (number)') %>% dplyr::select(`Threatened species`, ...3, ...4, ...5) %>% rename("region" = `Threatened species`, "Year" = ...3, "Species" = ...4, "Value" = ...5) %>% filter(Year == 2021) %>% mutate(Species = recode(Species, "Threatened Species: Plants (number)" = "Plants")) %>% dplyr::select(region, Value, Year) %>% dplyr::select(region, Value) 
```



```{r, echo=FALSE, message=FALSE}

mapdata <- map_data("world") ##ggplot2
View(mapdata)
mapdata <- left_join(mapdata, sp1, by = "region")
View(mapdata)

mapdata1<-mapdata %>% filter(!is.na(mapdata$Value))
View(mapdata1)

map1<-ggplot(mapdata1, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = Value), color = "black") + theme(legend.position = "center")
map1
```


```{r, echo=FALSE, message=FALSE}

map1<-ggplot(mapdata1, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = Value), color = "black") + theme(legend.position = "left") + theme_bw()
map1
```